version: "3.8"

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=url_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
    volumes:
      - ./storage/postgres-data:/var/lib/postgresql/data
    networks:
      - djangonetwork
  url_short:
    build: ./url_shortener
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=url_db
      - DB_USER=postgres
      - DB_PASSWORD=123
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db
    links:
      - db:db
    networks:
      - djangonetwork

networks:
  djangonetwork:
    driver: bridge