# Generated by Django 3.2.4 on 2021-06-18 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_link', models.URLField()),
                ('short_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
